version: "3.9"

services:
  express-server:
    image: "localhost:50001/digit-tally-app-backend:latest"
    secrets: &backend-secret
      - source: backend-env
        target: /app/.env
        uid: '103'
        gid: '103'
        mode: 0440
    networks:
      - digit-tally-network
    deploy: &deploy
      mode: replicated
      replicas: 1
      rollback_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: pause
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback

  web-events:
    image: "localhost:50001/digit-tally-app-notificationv2:latest"
    secrets:  *backend-secret
    depends_on:
      - express-server
    networks:
      - digit-tally-network
    deploy:
      << : *deploy
      mode: replicated
      replicas: 1 
       
  web:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.production.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8888:80
    command: [ nginx-debug, '-g', 'daemon off;' ]
    depends_on:
      - express-server
      -  web-events
    networks:
      - digit-tally-network
    deploy:
      << : *deploy
      mode: replicated
      replicas: 1 

networks:
  digit-tally-network:
    external: true

secrets:
  backend-env:
    external: true
