import StatusCode from 'http-status-codes';

export const ERROR: Record<string, [string, number]> = {
  unacceptableBackupPassword: [
    'The backup password and hint cannot be the same',
    StatusCode.BAD_REQUEST,
  ],
  invalidPassword: [
    'Password must be at least 8 characters long, and it must contain at least one uppercase letter, one lowercase letter, one number and one special character',
    StatusCode.BAD_REQUEST,
  ],
  emailExist: ['An account with the email exists', StatusCode.CONFLICT],
  waitlistEmailExist: ['Your email is already in the waitlist', StatusCode.CONFLICT],
  superAdminExist: ['Superadmin account created already', StatusCode.CONFLICT],
  noSuperAdmin: ['Access denied', StatusCode.FORBIDDEN],
  employeeEmailExist: [
    'The email is already associated to an employee account in an organization',
    StatusCode.CONFLICT,
  ],
  noBusinessData: ['Business data is required', StatusCode.BAD_REQUEST],
  emailServiceFail: [
    'Email Service Unavailable - Internet Connection Error',
    StatusCode.SERVICE_UNAVAILABLE,
  ],
  googleAccountExist: ['Google account exists', StatusCode.CONFLICT],
  backupPasswordExist: ['Backup password exists', StatusCode.CONFLICT],
  noEmail: ['Email not registered. Please sign up', StatusCode.NOT_FOUND],
  zeroAmount: ['Total amount can not be zero', StatusCode.BAD_REQUEST],
  noEmailAndId: ['No account associated with the email and id', StatusCode.NOT_FOUND],
  invalidOTP: ['The verification code is invalid or has expired', StatusCode.UNAUTHORIZED],
  noRefreshToken: ['Access Denied. No refresh token provided.', StatusCode.UNAUTHORIZED],
  notAuthorized: ['You are not authorized', StatusCode.UNAUTHORIZED],
  noPermission: ['You are not authorized for this action.', StatusCode.FORBIDDEN],
  emailVerified: ['Email is already verified', StatusCode.BAD_REQUEST],
  invalidSecret: ['Invalid secret key', StatusCode.BAD_REQUEST],
  activeUser: ['User in active state', StatusCode.CONFLICT],
  _2faEnabled: [
    'Two-factor authentication for the account is already enabled',
    StatusCode.CONFLICT,
  ],
  _2faNotEnabled: [
    'Two-factor authentication is not enabled for your account',
    StatusCode.FORBIDDEN,
  ],
  _2faError: ['Unable to enable Two-factor authentication', StatusCode.FORBIDDEN],
  _2faFailed: [
    'Two-Factor Authentication (2FA) verification failed. Please enter the correct authentication code to proceed',
    StatusCode.FORBIDDEN,
  ],
  _2faRequired: [
    'Two-Factor Authentication (2FA) is required for this account',
    StatusCode.FORBIDDEN,
  ],
  backupPasswordRequired: ['Backup password is required for this account', StatusCode.FORBIDDEN],
  noUser: ['No user found', StatusCode.NOT_FOUND],
  unverifiedEmail: [
    'Email not verified. Check inbox/spam or request new OTP to verify your account',
    StatusCode.FORBIDDEN,
  ],
  passwordConflict: [
    'Your new password cannot be the same as your current password. Please enter a different password.',
    StatusCode.CONFLICT,
  ],
  inactiveAccount: [
    'Your account is not active, kindly activate your account',
    StatusCode.FORBIDDEN,
  ],
  noBackupPassword: ['No backup password set for this account', StatusCode.FORBIDDEN],
  unverifiedAccount: [
    'Your account is not verified, kindly verify your account',
    StatusCode.FORBIDDEN,
  ],
  invalidEmailOrPassword: ['Email or Password is incorrect', StatusCode.UNAUTHORIZED],
  invalidBackupPassword: ['Backup password is incorrect', StatusCode.UNAUTHORIZED],
  invalidUserId: ['Invalid user id', StatusCode.BAD_REQUEST],
  invalidPasswordVerification: ['Password incorrect', StatusCode.UNAUTHORIZED],
  unverifiedGmailAccount: ['Your gmail account is currently not verified', StatusCode.FORBIDDEN],
  invalidToken: ['Invalid or unaccepted Token', StatusCode.UNAUTHORIZED],
  invalidOldPwd: ['Incorrect old Password', StatusCode.UNAUTHORIZED],
  noBank: ['No bank account found', StatusCode.NOT_FOUND],
  inactiveBank: ['The bank account is not active', StatusCode.UNAUTHORIZED],
  noCustomer: ['No customer found', StatusCode.NOT_FOUND],
  notInvoice: ['Document type must be an invoice', StatusCode.BAD_REQUEST],
  noInvoice: ['No document with the invoice id', StatusCode.NOT_FOUND],
  noCurrency: [
    'Currency is required. Kindly update it on  your profile page.',
    StatusCode.BAD_REQUEST,
  ],
  invalidDocument: ['You cannot link a draft document', StatusCode.BAD_REQUEST],
  paymentCompleted: ['You have completed your payment', StatusCode.BAD_REQUEST],
  usedInvoice: ['The invoice has been used to create a creditnote', StatusCode.BAD_REQUEST],
  noDraftDocument: ['No draft document found with the id', StatusCode.NOT_FOUND],
  noDocument: ['No document found', StatusCode.NOT_FOUND],
  noNotification: ['No notification found', StatusCode.NOT_FOUND],
  invalidDocumentType: ['Invalid document type', StatusCode.BAD_REQUEST],
  invalidStatus: ['Invalid status', StatusCode.BAD_REQUEST],
  invalidEntity: ['Invalid entity type', StatusCode.BAD_REQUEST],
  invalidAction: ['Invalid action', StatusCode.BAD_REQUEST],
  invalidImageType: ['Invalid image data type', StatusCode.BAD_REQUEST],
  deleteContactError: ['Error in deleting contacts', StatusCode.BAD_REQUEST],
  deleteItemsError: ['Error in deleting items', StatusCode.BAD_REQUEST],
  noItem: ['No item found', StatusCode.NOT_FOUND],
  noPlan: ['Subscription plan not found.', StatusCode.NOT_FOUND],
  noDevice: ['Device not found', StatusCode.NOT_FOUND],
  noService: ['Service not found', StatusCode.NOT_FOUND],
  existInvoiceNumber: ['Invoice number exists.', StatusCode.CONFLICT],
  requireCustomerId: ['Customer Id is required', StatusCode.BAD_REQUEST],
  invalidArchiveDocType: ['Document selected can not be archived', StatusCode.BAD_REQUEST],
  archiveMode: ['Document is in archive mode', StatusCode.FORBIDDEN],
  notArchived: ['Document is not in archive mode', StatusCode.CONFLICT],
  archived: ['Document is in archived already', StatusCode.CONFLICT],
  rateLimitExceeded: ['Attempts exceeded', StatusCode.TOO_MANY_REQUESTS],
  serverError: ['An unknown error occured', StatusCode.INTERNAL_SERVER_ERROR],
  invalidReminderDocument: [
    'You can only send a reminder with an invoice document',
    StatusCode.BAD_REQUEST,
  ],
};
